"use strict";
const test = require("node:test"), assert = require("node:assert/strict"), fs = require("node:fs/promises"), os = require("node:os"), path = require("node:path");
const { createResearchProjectStore, portableProject, parsePortableProject, normalizeProject } = require("./zerothink-projects.cjs");
const seed = () => ({ title: "Actual project", question: "What does this source support?", processId: "evidence-map", maxPasses: 3, useModel: false, zeroMode: true, autoWeb: false, documents: [{ id: "00000000-0000-4000-8000-000000000001", title: "Source", text: "private evidence" }], result: null, status: "draft", lastError: "" });
async function fixture(t) { const dir = await fs.mkdtemp(path.join(os.tmpdir(), "zt-projects-")); t.after(() => fs.rm(dir, { recursive: true, force: true })); const filePath = path.join(dir, "projects.json"), storage = { encryptString: (s) => Buffer.from(s).map((v) => v ^ 42), decryptString: (b) => Buffer.from(b).map((v) => v ^ 42).toString() }; return { filePath, store: createResearchProjectStore({ filePath, storage, secure: () => true }), storage }; }
test("encrypted project save, reopen, edit and delete retain fields without plaintext", async (t) => { const { store, filePath } = await fixture(t); const p = await store.saveProject(seed()); assert.equal((await store.getProject(p.id)).question, seed().question); assert.equal((await store.listProjects())[0].sourceCount, 1); assert.ok(!(await fs.readFile(filePath, "utf8")).includes("private evidence")); await store.saveProject({ ...p, title: "Edited" }); assert.equal((await store.getProject(p.id)).title, "Edited"); await store.deleteProject(p.id); assert.equal(await store.getProject(p.id), null); });
test("running projects reopen as interrupted, without a fabricated result", async (t) => { const { store } = await fixture(t); const p = await store.saveProject({ ...seed(), status: "running" }); const saved = await store.getProject(p.id); assert.equal(saved.status, "interrupted"); assert.equal(saved.result, null); assert.match(saved.lastError, /not automatically resumed/); });
test("portable import uses new identity, bounded schema and no device or credential metadata", () => { const p = normalizeProject({ ...seed(), apiKey: "DO_NOT_COPY", absolutePath: "C:\\private", providerUrl: "https://private" }); const json = portableProject(p); assert.ok(!json.includes("DO_NOT_COPY")); assert.ok(!json.includes("absolutePath")); assert.ok(!json.includes("providerUrl")); const imported = parsePortableProject(json); assert.notEqual(imported.id, p.id); assert.deepEqual(imported.documents, p.documents); assert.throws(() => parsePortableProject("x".repeat(4 * 1024 * 1024 + 1))); assert.throws(() => parsePortableProject('{"version":1}')); });
test("concurrent saves serialize and corrupt storage is preserved", async (t) => { const { store, filePath } = await fixture(t); await Promise.all(Array.from({ length: 4 }, (_, i) => store.saveProject({ ...seed(), title: `Project ${i}` }))); assert.equal((await store.listProjects()).length, 4); await fs.writeFile(filePath, "broken"); await assert.rejects(store.saveProject(seed())); assert.equal(await fs.readFile(filePath, "utf8"), "broken"); });
test("unsafe storage and malformed process/source options fail closed", async (t) => { const { storage, filePath } = await fixture(t); const store = createResearchProjectStore({ storage, filePath, secure: () => false }); await assert.rejects(store.saveProject(seed()), /Secure/); assert.throws(() => normalizeProject({ ...seed(), maxPasses: 10 })); assert.throws(() => normalizeProject({ ...seed(), documents: Array.from({ length: 9 }, (_, i) => ({ ...seed().documents[0], id: `00000000-0000-4000-8000-${String(i).padStart(12, "0")}` })) })); });
