import { useEffect, useState } from "react";
type Props = { disabled: boolean; active: ZeroThinkResearchProject | null; revision: number; onCreate: (name: string) => Promise<void>; onOpen: (project: ZeroThinkResearchProject) => Promise<void>; onMessage: (text: string) => void; onDeleted: (id: string) => void; onBeforeAction: () => Promise<void> };
export default function ZeroThinkProjects({ disabled, active, revision, onCreate, onOpen, onMessage, onDeleted, onBeforeAction }: Props) {
  const [projects, setProjects] = useState<ZeroThinkResearchProjectSummary[]>([]), [name, setName] = useState(""), [working, setWorking] = useState(false), [error, setError] = useState("");
  const api = window.zeroOne as typeof window.zeroOne & ZeroThinkProjectsAPI;
  async function refresh() { setProjects(await api.listZeroThinkProjects()); }
  useEffect(() => { let alive = true; api.listZeroThinkProjects().then((value) => { if (alive) setProjects(value); }).catch((e) => { if (alive) setError(e instanceof Error ? e.message : "Projects could not open."); }); return () => { alive = false; }; }, [revision]);
  async function act(action: () => Promise<void>) { setWorking(true); setError(""); try { await onBeforeAction(); await action(); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Project operation failed. Existing work was preserved."); } finally { setWorking(false); } }
  return <section className="zt-inline-setup" aria-label="Saved research projects"><div className="zt-panel-head"><strong>Research projects · {projects.length}/32</strong><span>{active ? `Autosave: ${active.title}` : "Choose a project to enable autosave"}</span></div><p>Question, process, depth, options, selected source text and latest completed result are encrypted on this device. Interrupted runs reopen for review; they do not automatically restart.</p><div className="zt-web-search"><input value={name} maxLength={160} onChange={(e) => setName(e.target.value)} placeholder="Name this research project" aria-label="Research project name" disabled={disabled || working} /><button disabled={disabled || working || !name.trim()} onClick={() => void act(async () => { await onCreate(name.trim()); setName(""); })}>Save current as project</button><button disabled={disabled || working} onClick={() => void act(async () => { const p = await api.importZeroThinkProject(); if (p) { await onOpen(p); onMessage("Portable project imported. Review its sources and settings before running."); } })}>Import project JSON</button></div><div className="zt-library-items">{projects.map((p) => <article key={p.id}><strong>{p.title}</strong><small>{p.sourceCount} sources · {p.status} · {new Date(p.updatedAt).toLocaleString()}</small><button disabled={disabled || working} onClick={() => void act(async () => { const project = await api.getZeroThinkProject(p.id); if (project) await onOpen(project); })}>{active?.id === p.id ? "Reopen saved version" : "Open project"}</button><button disabled={disabled || working} onClick={() => void act(async () => { if (await api.exportZeroThinkProject(p.id).then((r) => r.saved)) onMessage("Portable project exported as readable JSON. It includes source text and report; protect private content."); })}>Export project</button><button disabled={disabled || working} onClick={() => { if (window.confirm("Remove this saved research project? Export it first. Library sources and conversations remain.")) void act(async () => { await api.deleteZeroThinkProject(p.id); onDeleted(p.id); onMessage("Saved project removed. Its conversation and library sources remain."); }); }}>Remove</button></article>)}</div>{error && <p role="alert">{error}</p>}<small>Export is readable JSON with selected evidence. Vault keys and device configuration are excluded; anything typed into your question, source text or answer remains content. Imports never trigger model, web or computer actions.</small></section>;
}
